### ISSUE TITLE
Badge - better support for MD syntax

### ISSUE THREAD

**Issue by Kielek** [self-actuated/docs.actuated.dev#18]
## Proposed change
Modify faq.md file to allow use markdown friendly badges.

I see two potentials options:

First, using common shields.io portal to generate such badges:
```md
[![Arm CI sponsored by Actuated](https://img.shields.io/badge/SA_actuated.dev-004BDD)](https://actuated.dev/)
```

which results to [![Arm CI sponsored by Actuated](https://img.shields.io/badge/SA_actuated.dev-004BDD)](https://actuated.dev/).

Second, you can add image in the correct size to image folder and support something like (no preview, as image does not exist):

```md
[![Arm CI sponsored by Actuated](https://docs.actuated.dev/images/actuated-badge-120.png)](https://actuated.dev/)
```

If you are fine with first option I can rise the PR based on: https://github.com/self-actuated/docs.actuated.dev/compare/master...Kielek:docs.actuated.dev:md-badge-support?expand=1

## Context
PR for OpenTelemetry Automatic Instrumentation introducing support for ARM64 (thanks for supporting machines!). https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3277

Current requirements, force us to allow html syntax in documentation files. If possible, it will be great to avoid this.

**Comment by Kielek** [comment]
@alexellis, @welteki, could you please check?

**Comment by alexellis** [comment]
Hi @Kielek I like the markdown version and am happy for you to send that PR and use that version for OTEL.
